### ISSUE TITLE
💕新功能建议💕

### ISSUE THREAD

**Issue by RedElectricity** [chinosk114514/Arcaea_playdata_web#1]
能不能把写入数据库的程序写出来，不要yyy，谢绝yyy，另外给你💕（

💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕💕

**Comment by chinosk114514** [comment]
yyy怎么了yyy怎么了yyy怎么了yyy怎么了,另外谢谢你的💕(

**Comment by RedElectricity** [comment]
yyy难读，yyy难度，yyy难读
